name: dpo
trainer: pairwise
objective: dpo
train_batch_size: 1
eval_batch_size: 1
learning_rate: 1.0e-4
max_steps: 10
gradient_accumulation_steps: 16
max_sequence_length: 384
beta: 0.1
label_smoothing: 0.0
